name: Trigger auto deployment for test0826

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test0826-AutoDeployTrigger-64276809-7e54-4899-910b-1000bf9c9a9d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TEST0826_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TEST0826_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TEST0826_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.TEST0826_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TEST0826_REGISTRY_PASSWORD }}
          containerAppName: test0826
          resourceGroup: ACAtest0826
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


